web_inicio:
    path:     /
    defaults: { _controller: WebBundle:Inicio:inicio }

web_login:
    path:     /admin/
    defaults: { _controller: WebBundle:Login:login }

web_login_check:
    path:     /admin/check/
    defaults: { _controller: WebBundle:Login:loginCheck }

web_logout:
    path:     /admin/logout/
    defaults: { _controller: WebBundle:Login:logout }

# FUNCIONE AJAX
ajax_guardar_servicio:
    path:     /admin/guardar-servicio/
    defaults: { _controller: WebBundle:Inicio:guardarServicio }
    options:
        expose: true

ajax_eliminar_servicio:
    path:     /admin/eliminar-servicio/
    defaults: { _controller: WebBundle:Inicio:eliminarServicio }
    options:
        expose: true

ajax_guardar_producto:
    path:     /admin/guardar-producto/
    defaults: { _controller: WebBundle:Inicio:guardarProducto }
    options:
        expose: true

ajax_guardar_foto_producto:
    path:     /admin/guardar-foto-producto/
    defaults: { _controller: WebBundle:Inicio:guardarFotoProducto }
    options:
        expose: true

ajax_eliminar_producto:
    path:     /admin/eliminar-producto/
    defaults: { _controller: WebBundle:Inicio:eliminaProducto }
    options:
        expose: true

ajax_enviar_contacto:
    path:     /enviar-contacto/
    defaults: { _controller: WebBundle:Inicio:enviarContacto }
    options:
        expose: true